<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<script type="text/javascript">
    console.log('success');
</script>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

	<?php switch($this->getPaymentType()):
            case 'pagseguro_online_debit':?>
                <?php if(!is_null($this->getPaymentLink())): ?>
                        <div class="actions-toolbar">
                        <div class="primary">
                            <a class="action primary continue" target="_blank" href="<?php /* @escapeNotVerified */ echo $this->getPaymentLink() ?>"><span><?php /* @escapeNotVerified */ echo __('Ir para o site do banco') ?></span></a>
                        </div>
                </div>
                <?php endif; ?>
            <?php break; ?>

            <?php case 'pagseguro_boleto':?>
                <?php if(!is_null($this->getPaymentLink())): ?>
                        <div class="actions-toolbar">
                        <div class="primary">
                            <a class="action primary continue" target="_blank" href="<?php /* @escapeNotVerified */ echo $this->getPaymentLink() ?>"><span><?php /* @escapeNotVerified */ echo __('Imprimir boleto') ?></span></a>
                        </div>
                </div>
                <?php endif; ?>
            <?php break; ?>

            <?php default:?>
                <div class="actions-toolbar">
                        <div class="primary">
                            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue comprando') ?></span></a>
                        </div>
                </div>
            <?php break; ?>

	<?php endswitch; ?>

</div>
