<div class="col-m-12">
    <p>Com esta funcionalidade você poderá listar as suas transações. Caso não encontre uma transação ou se o status de uma transação estiver desatualizada é aconselhável que você use a <a id="link-conciliation" href='$url'><u>conciliação</u></a> de transações.</p>
    <p><strong>Atenção: </strong>Toda transação estornada de forma parcial não tem seu status alterado. Por isso, ao filtrar por "Estornada Parcialmente" o pedido exibirá o seu status original.</p>
</div>