<div class="admin__data-grid-header-row">
    <div class="admin__filter-actions">
        <select id="conciliation-days" class="admin__control-select">
            <option value="5" selected="selected">5</option>
            <option value="10">10</option>
            <option value="15">15</option>
            <option value="20">20</option>
            <option value="25">25</option>
            <option value="30">30</option>
        </select>
        <button id="conciliation-search" title="Search" type="button" class="action-default scalable action-secondary">
            <span>Pesquisar</span>
        </button>
        <div class="admin__data-grid-pager-wrap">
            <button id="conciliation-conciliate" title="Search" type="button" class="action-default scalable action-secondary" disabled>
                <span>Conciliar</span>
            </button>
        </div>
    </div>
</div>
