<div class="col-m-12">
    <p>Com esta funcionalidade você poderá estornar os valores de transações que estejam nos status “Paga”, “Disponível” e “Em disputa”. É aconselhável que antes de usar esta funcionalidade você faça a conciliação de suas transações para obter os status mais atuais.</p>
    <p>
        <strong>Atenção: </strong>Ao realizar um <strong>Estorno total</strong> a transação será estornada e terá seu status alterado no PagSeguro para
            "Devolvida". Ao realizar um <strong>Estorno parcial</strong> será estornado o valor inserido, contudo, o status da transação no PagSeguro não será
            alterado (a transação manterá o seu último status).
    </p>
</div>