
<div>
    <h2>Formas de pagamento</h2>
</div>
<div class="panel with-nav-tabs panel-default">
    <div id="tabs" class="panel-heading">

            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#tab1default" data-toggle="tab">
                        <i class="fa fa-credit-card fa-4x"></i>
                        <span>Cartão de Crédito</span>
                        <span class="btn btn-primary"> selecione </span>
                    </a>
                </li>
                <li>
                    <a href="#tab2default" data-toggle="tab">
                        <i class="fa fa-money fa-4x"></i>
                        <span>Débito Online</span>
                        <span class="btn btn-primary"> selecione </span>
                    </a>
                </li>
                <li>
                    <a href="#tab3default" data-toggle="tab">
                        <i class="fa fa-barcode fa-4x"></i>
                        <span>Boleto</span>
                        <span class="btn btn-primary"> selecione </span>
                    </a>
                </li>
            </ul>
            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane fade" id="tab1default">

                        <div class="col-md-8 col-md-offset-3">
                            <form>
                                <!-- Text input-->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_cod">CPF/CNPJ</label>
                                    <div class="col-md-4">
                                        <input id="document-credit-card" name="document" type="text" placeholder="" class="form-control input-md">
                                    </div>
                                </div>

                                <!-- Text input-->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_num">Número do cartão</label>
                                    <div class="col-md-4">
                                        <input id="card_num" name="card_num" type="text" placeholder="" class="form-control input-md" required="">

                                    </div>
                                </div>

                                <!-- Text input-->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_holder_name">Nome impresso no cartão</label>
                                    <div class="col-md-4">
                                        <input id="card_holder_name" name="card_holder_name" type="text" placeholder="" class="form-control input-md" required="">
                                    </div>
                                </div>
                                
                                <!-- Holder birthdate -->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_holder_birthdate">Data de nascimento</label>
                                    <div class="col-md-4">
                                        <input id="card_holder_birthdate" name="card_holder_birthdate" type="text" placeholder="" class="form-control input-md" required="">
                                    </div>
                                </div>

                                <!-- Select Basic -->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_validate">Validade</label>
                                    <div class="col-md-2">
                                        <select id="card_expiration_month" name="card_validate" class="form-control">
                                            <option value="" disabled selected>Mês</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                            <option value="07">07</option>
                                            <option value="08">08</option>
                                            <option value="09">09</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <select id="card_expiration_year" name="card_validate" class="form-control">
                                            <option value="" disabled selected>Ano</option>
                                            <?php 
                                                $year = idate("Y");
                                                $maxYear = $year + 20;
                                                for ($i = $year; $i < $maxYear; $i++): ?>
                                            <option value="<?=$i;?>"><?=$i;?></option>
                                            <?php endfor; ?>
                                        </select>
                                    </div>
                                </div>

                                <!-- Text input-->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_cod">Código de segurança</label>
                                    <div class="col-md-4">
                                        <input id="card_cod" name="card_cod" type="text" placeholder="" class="form-control input-md">
                                    </div>
                                </div>

                                <!-- Installments -->
                                <div class="form-group row display-none">
                                    <label class="col-md-4 control-label" for="card_installments">Parcelas</label>
                                    <div class="col-md-4">
                                        <select id="card_installments" name="card_installments" class="form-control">
                                            <option value="" disabled selected>Escolha o N° de parcelas</option>
                                        </select>
                                    </div>
                                    
                                </div>
                                
                                <!-- Total -->
                                <div class="form-group row display-none">    
                                    <div class="col-md-2 col-md-offset-3 ">
                                        Total: R$<span id="card_total"></span>  
                                    </div>
                                </div>
                                
                            </form>
                        </div>
                        <!-- Text input-->
                        <div class="form-group row has-btn">

                            <button class="btn btn-block btn-primary" id="payment-credit-card"> Pagar com cartão de crédito </button>

                        </div>
                    </div>
                    <div class="tab-pane fade" id="tab2default">
                        <div class="col-md-8 col-md-offset-3">

                            <form>
                                <!-- Text input-->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_cod">CPF/CNPJ</label>
                                    <div class="col-md-4">
                                        <input id="document-debit" name="document" type="text" placeholder="" class="form-control input-md">

                                    </div>
                                </div>
                                <p>Escolha seu banco abaixo onde deverá fazer o pagamento online.</p>
                                <fieldset id="bankList" class="form-group">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="bank" id="optionsRadios1" value="1" checked>
                                            Itaú
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="bank" id="optionsRadios2" value="2">
                                            Bradesco
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="bank" id="optionsRadios2" value="3">
                                            Santander
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="bank" id="optionsRadios2" value="4">
                                            Banco do Brasil'#card_expiration_month').val();
                                        </label>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                        <!-- Text input-->
                        <div class="form-group row has-btn">
                            <button class="btn btn-block btn-primary" id="payment-debit"> Pagar com débito online </button>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="tab3default">
                        <div class="col-md-8 col-md-offset-3">

                            <form>
                                <!-- Text input-->
                                <div class="form-group row">
                                    <label class="col-md-4 control-label" for="card_cod">CPF/CNPJ</label>
                                    <div class="col-md-4">
                                        <input id="document-boleto" name="document" type="text" placeholder="" class="form-control input-md">

                                    </div>
                                </div>
                            </form>

                            <p>Imprima o boleto e pague no banco</p>
                            <p>ou pague pela internet utilizando o código de barras do boleto</p>
                            <p>o prazo de validade do boleto é de 1 dia útil</p>
                        </div>
                        <!-- Text input-->
                        <div class="form-group row has-btn">
                            <button class="btn btn-block btn-primary" id="payment-boleto"> Pagar com boleto</button>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
<input type="hidden" id="adminurl" data-target="<?=$this->getBaseUrl(); ?>"/>
<input type="hidden" id="order" data-target="<?=$this->getOrder(); ?>"/>
<input type="hidden" id="session-code" data-target="<?=$this->getData('sessionCode'); ?>"/>
<input type="hidden" id="card-international" data-target=""/>
<input type="hidden" id="card-brand" data-target=""/>

<script type="text/javascript" src="<?=$this->getData('paymentUrl'); ?>"></script>
<script type="text/javascript">
    require([
            'jquery',
            'jquery/ui',
            "public"
        ],
        function($, tabs) {

            $("#tabs").tabs();
            
            //Update the total value according with installments
            $('#card_installments').on('change', function(){
                $('#card_total').text(this.value)
            });

            function loadElements(service, bank = false, creditCard = false)
            {

                $("#payment-"+service).trigger('processStart');

                var data = new Array();
                data['url'] = $('#adminurl').attr('data-target');
                data['orderId'] = $('#order').attr('data-target');
                data['sessionCode'] = $('#session-code').attr('data-target');
                data['document'] = $('#document-'+service).val();

                if (bank) {
                    var bankId = $("#bankList input[type='radio']:checked");
                    if (bankId.length > 0) {
                        data['bank'] = bankId.val();
                    }
                }
                
                if (creditCard) {
                    data['cardInternational'] = $('#card-international').attr('data-target');
                    data['installmentQuantity'] = $("#card_installments option:selected" ).attr('data-quantity');
                    data['installmentAmount'] = $("#card_installments option:selected" ).attr('data-amount');
                    data['holderName'] = $('#card_holder_name').val();
                    data['holderBirthdate'] = $('#card_holder_birthdate').val();
                }
                
                return data;
            }

            $('#payment-boleto').on('click', function(){
                var el = loadElements('boleto');
                PagSeguroDirectPayment.setSessionId(el.sessionCode);
                var hash = PagSeguroDirectPayment.getSenderHash();
                setTimeout(function () {
                    WS.Ajax.Direct.Boleto.Payment(el.url, el.orderId, hash, el.document);
                }, 5000);

            });

            $('#payment-debit').on('click', function(){
                var el = loadElements('debit', true);
                PagSeguroDirectPayment.setSessionId(el.sessionCode);
                var hash = PagSeguroDirectPayment.getSenderHash();
                setTimeout(function () {
                    WS.Ajax.Direct.OnlineDebit.Payment(el.url, el.orderId, hash, el.document, el.bank);
                }, 5000);
            });
            
            $('#payment-credit-card').on('click', function(){
                //PagSeguroDirectPayment.setSessionId(el.sessionCode);

                PagSeguroDirectPayment.createCardToken({ 
                    cardNumber: $('#card_num').val(),
                    brand: $('#card-brand').attr('data-target'), 
                    internationalMode: $('#card-international').attr('data-target'),
                    cvv: $('#card_cod').val(), 
                    expirationMonth: $('#card_expiration_month').val(), 
                    expirationYear: $('#card_expiration_year').val(),
                    success: function(response) { 
                        var el = loadElements('credit-card', false, true);
                        var token = response.card.token;
                        var hash = PagSeguroDirectPayment.getSenderHash();

                        setTimeout(function () {
                            WS.Ajax.Direct.CreditCard.Payment(
                                el.url,
                                el.orderId,
                                hash,
                                el.document,
                                token,
                                el.cardInternational,
                                el.installmentQuantity,
                                el.installmentAmount,
                                el.holderName,
                                el.holderBirthdate
                            );
                        }, 5000);
                    },
                    error: function(response) {
                        //console.log(response);
                    }
                });
            });
            
            //Get the installments and the credit card brand
            $('#card_num').on("blur", function() {
                PagSeguroDirectPayment.setSessionId($('#session-code').attr('data-target'));

                PagSeguroDirectPayment.getBrand({
                    cardBin: $('#card_num').val().substring(0,6),
                    internationalMode: true,
                    success: function(response) {
                        setTimeout(function () {
                            WS.Ajax.Direct.CreditCard.Installments(
                                $('#adminurl').attr('data-target'),
                                $('#order').attr('data-target'),
                                response.brand.name,
                                response.brand.international
                            );
                        }, 1500);
                    }
                });
            });
        }
    );
</script>