<section class="wrapper">
    <h2 class="title-payment">Formas de pagamento</h2>
    <h4 class="method-payment">Escolha o método</h4>
    <nav class="tabs-pagseguro clearfix" id="tabs-payment">
        <ul class="items clearfix">
            <li class="item --active">
                <a class="action js-tab-action" href="#credit-card">
                    <i class="fa fa-credit-card fa-4x"></i>
                    <span class="name">Cartão de Crédito</span>
                </a>
            </li><!-- /.item -->
            <li class="item">
                <a class="action js-tab-action" href="#debit-online">
                    <i class="fa fa-money fa-4x"></i>
                    <span class="name">Débito Online</span>
                </a>
            </li><!-- /.item -->
            <li class="item">
                <a class="action js-tab-action" href="#bilet">
                    <i class="fa fa-barcode fa-4x"></i>
                    <span class="name">Boleto</span>
                </a>
            </li><!-- /.item -->
        </ul><!-- /.items -->
    </nav><!-- /.tabs-payment -->
    <div class="tabs-content">
        <div class="item-tab --current" id="credit-card">
            <h3 class="title-tab">Cartão de Crédito</h3>
            <form class="form-horizontal clearfix" name="form-credit">
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 control-label" for="card_num">Número do cartão</label>
                    <div class="col-xs-12 col-sm-10">
                        <input class="form-control" id="card_num" name="card_num" type="text" required>
                    </div>
                </div><!-- /.form-group -->
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 control-label" for="card_holder_name">Nome impresso no cartão</label>
                    <div class="col-xs-12 col-sm-10">
                        <input class="form-control" id="card_holder_name" name="card_holder_name" type="text" required>
                    </div>
                </div><!-- /.form-group -->
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 control-label" for="card_validate">Validade</label>
                    <div class="col-xs-12 col-sm-10">
                        <div class="row form-inline-childs">
                            <div class="col-xs-12 col-sm-6">
                                <select class="form-control" id="card_validate" name="card_validate">
                                    <option value="" disabled selected>Mês</option>
                                    <option value="01">01</option>
                                    <option value="02">02</option>
                                    <option value="03">03</option>
                                    <option value="04">04</option>
                                    <option value="05">05</option>
                                    <option value="06">06</option>
                                    <option value="07">07</option>
                                    <option value="08">08</option>
                                    <option value="09">09</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <select id="card_validate" name="card_validate" class="form-control">
                                    <option value="" disabled selected>Ano</option>
                                    <?php for ($i = 2016; $i < 2035; $i++): ?>
                                    <option value="<?=$i;?>"><?=$i;?></option>
                                    <?php endfor; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div><!-- /.form-group -->
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 control-label" for="card_cod">Código de segurança</label>
                    <div class="col-xs-12 col-sm-10">
                        <input class="form-control" id="card_cod" name="card_cod" type="text">
                    </div>
                </div><!-- /.form-group -->
                <button class="btn-pagseguro --align-right" id="payment-credit-card">Concluir</button>
            </form>
        </div><!-- /.item-tab#credit-card -->
        <div class="item-tab" id="debit-online">
            <h3 class="title-tab">Débito On-line</h3>
            <form class="form-horizontal clearfix" name="form-debit">
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 control-label" for="card_cod">CPF/CNPJ</label>
                    <div class="col-xs-12 col-sm-10">
                        <input class="form-control" id="document-debit" name="document" type="text">
                    </div>
                </div><!-- /.form-group -->
                <div class="form-group">
                    <label class="col-xs-12 col-sm-4 control-label">Escolha seu banco abaixo onde deverá fazer o pagamento online.</label>
                    <div class="col-xs-12 col-sm-8">
                        <label class="radio-inline">
                            <input type="radio" name="bank" id="optionsRadios1" value="1" checked>
                            Itaú
                        </label>
                        <label class="radio-inline">
                            <input type="radio" name="bank" id="optionsRadios2" value="2">
                            Bradesco
                        </label>
                    </div>
                    <div class="col-xs-12 col-sm-8">
                        <label class="radio-inline">
                            <input type="radio" name="bank" id="optionsRadios2" value="3">
                            Santander
                        </label>
                        <label class="radio-inline">
                            <input type="radio" name="bank" id="optionsRadios2" value="4">
                            Banco do Brasil
                        </label>
                    </div>
                </div><!-- /.form-group -->
                <button class="btn-pagseguro --align-right" id="payment-debit">Concluir</button>
            </form>
        </div><!-- /.item-tab#debit-online -->
        <div class="item-tab" id="bilet">
            <h3 class="title-tab">Boleto</h3>
            <form class="form-horizontal clearfix" name="form-bilit">
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 control-label" for="card_cod">CPF/CNPJ</label>
                    <div class="col-xs-12 col-sm-10">
                        <input class="form-control" id="document-boleto" name="document" type="text">
                    </div>
                </div>
                <button class="btn-pagseguro --align-right" id="payment-boleto">Concluir</button>
            </form>
            <ul class="list-warning">
                <li>Imprima o boleto e pague no banco</li>
                <li>Ou pague pela internet utilizando o código de barras do boleto</li>
                <li>o prazo de validade do boleto é de 1 dia útil</li>
            </ul>
        </div><!-- /.item-tab#bilet -->
    </div><!-- /.tabs-content-->
</section><!-- /.wrapper -->

<input type="hidden" id="adminurl" data-target="<?=$this->getBaseUrl(); ?>"/>
<input type="hidden" id="order" data-target="<?=$this->getOrder(); ?>"/>
<input type="hidden" id="session-code" data-target="<?=$this->getData('sessionCode'); ?>"/>

<script type="text/javascript" src="<?=$this->getData('paymentUrl'); ?>"></script>
<script type="text/javascript">
    require([
            'jquery',
            "public"
        ],
        function($) {
            ;(function tabsPagseguro($, undefined){
                var $action = $('.js-tab-action');
                $action.on('click', function(e){
                    e.preventDefault();
                    var $itemtTab = $(this).parent('.item');
                    var isActive = $itemtTab.hasClass('--active');

                    if(!isActive) {
                        var $newTabId = $($(this).attr('href'));
                        $('#tabs-payment .item.--active').removeClass('--active'); //remove class the old tab selected
                        $('.item-tab.--current').removeClass('--current');

                        //add new tab selected
                        $itemtTab.addClass('--active');
                        $newTabId.addClass('--current');
                    } else {
                        return false;
                    }
                });
            }($));


            function loadElements(service, bank = false)
            {

                $("#payment-"+service).trigger('processStart');

                var data = new Array();
                data['url'] = $('#adminurl').attr('data-target');
                data['orderId'] = $('#order').attr('data-target');
                data['sessionCode'] = $('#session-code').attr('data-target');
                data['document'] = $('#document-'+service).val();

                if (bank) {
                    var bankId = $("#bankList input[type='radio']:checked");
                    if (bankId.length > 0) {
                        data['bank'] = bankId.val();
                    }
                }
                return data;
            }

            $('#payment-boleto').on('click', function(){
                var el = loadElements('boleto');
                PagSeguroDirectPayment.setSessionId(el.sessionCode);
                var hash = PagSeguroDirectPayment.getSenderHash();
                setTimeout(function () {
                    WS.Ajax.Direct.Boleto.Payment(el.url, el.orderId, hash, el.document);
                }, 5000);

            });

            $('#payment-debit').on('click', function(){
                var el = loadElements('debit', true);
                PagSeguroDirectPayment.setSessionId(el.sessionCode);
                var hash = PagSeguroDirectPayment.getSenderHash();
                setTimeout(function () {
                    WS.Ajax.Direct.OnlineDebit.Payment(el.url, el.orderId, hash, el.document, el.bank);
                }, 5000);
            });
        }
    );
</script>
